main: pdl.insegura.PendulumPlugin
version: 1.3.0
name: Pendulum
author: iPancrema
api-version: 1.16

commands:
    pendulum:
        description: Comando principal del plugin de Pendulum.
        aliases: pdl
